# typed: false
# frozen_string_literal: true

# This file is generated by markcipolla/balance's release workflow. DO NOT EDIT.
class Balance < Formula
  desc "Anthropic Messages API proxy that pools Claude subscriptions and API keys"
  homepage "https://github.com/markcipolla/balance"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/markcipolla/balance/releases/download/v0.5.2/balance_0.5.2_darwin_amd64.tar.gz"
      sha256 "c16348ac310e2aeabb402f537685fac65e7d3f94f545a436cd861ab0c9b6480a"

      define_method(:install) do
        bin.install "balance"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/markcipolla/balance/releases/download/v0.5.2/balance_0.5.2_darwin_arm64.tar.gz"
      sha256 "a62cda15626d7deb0079502615763a5596d8d9f8da424d143be2046f75266748"

      define_method(:install) do
        bin.install "balance"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/markcipolla/balance/releases/download/v0.5.2/balance_0.5.2_linux_amd64.tar.gz"
      sha256 "6004ccdf79405ac905118e38021cd6759c3768c526d0e3949c1da06736baf5ed"
      define_method(:install) do
        bin.install "balance"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/markcipolla/balance/releases/download/v0.5.2/balance_0.5.2_linux_arm64.tar.gz"
      sha256 "c88cfae5511b225d98d6e402a8da882920e8404cab96e7adffae3fe4ad0f9f4b"
      define_method(:install) do
        bin.install "balance"
      end
    end
  end

  test do
    assert_match "balance 0.5.2", shell_output("#{bin}/balance --version")
  end
end
