# typed: false
# frozen_string_literal: true

# This file is generated by markcipolla/balance's release workflow. DO NOT EDIT.
class Balance < Formula
  desc "Anthropic Messages API proxy that pools Claude subscriptions and API keys"
  homepage "https://github.com/markcipolla/balance"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/markcipolla/balance/releases/download/v0.3.0/balance_0.3.0_darwin_amd64.tar.gz"
      sha256 "08b70e23011e597fb1f7731f8f545e75a43998977fc9b4dc4c28065877031608"

      define_method(:install) do
        bin.install "balance"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/markcipolla/balance/releases/download/v0.3.0/balance_0.3.0_darwin_arm64.tar.gz"
      sha256 "17bd424be3683255e95d901ae0930b3e5845344d16a0a47c3c44abdceb56f8e4"

      define_method(:install) do
        bin.install "balance"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/markcipolla/balance/releases/download/v0.3.0/balance_0.3.0_linux_amd64.tar.gz"
      sha256 "f1a091cc943bec215353ab280fe6af6bce2acd2d8c14560ea31f6d4540d2748c"
      define_method(:install) do
        bin.install "balance"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/markcipolla/balance/releases/download/v0.3.0/balance_0.3.0_linux_arm64.tar.gz"
      sha256 "49b6119cbe67e4fc055cfc6c047a2e64c3eea06fd17a76ba39c98df1fd6f4e59"
      define_method(:install) do
        bin.install "balance"
      end
    end
  end

  test do
    assert_match "balance 0.3.0", shell_output("#{bin}/balance --version")
  end
end
