# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diskclean < Formula
  desc "Interactive disk cleanup TUI for Docker, Dokploy and Ubuntu servers."
  homepage "https://github.com/markcipolla/diskclean"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/markcipolla/diskclean/releases/download/v0.1.0/diskclean_0.1.0_macos_amd64.tar.gz"
      sha256 "7cacde23a3c4a00cf3c4f2c768f31c3d9596c4e3ae778706fc87dd6d1e4c64a9"

      define_method(:install) do
        bin.install "diskclean"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/markcipolla/diskclean/releases/download/v0.1.0/diskclean_0.1.0_macos_arm64.tar.gz"
      sha256 "9a86bc7464197f386e74f957d3a498686f5a478cf862c95bf36f2e1909bf3077"

      define_method(:install) do
        bin.install "diskclean"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/markcipolla/diskclean/releases/download/v0.1.0/diskclean_0.1.0_linux_amd64.tar.gz"
      sha256 "f4550f386730cf52168de5f616574fe35185449c1782a94bf8a9e648c99dc451"
      define_method(:install) do
        bin.install "diskclean"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/markcipolla/diskclean/releases/download/v0.1.0/diskclean_0.1.0_linux_arm64.tar.gz"
      sha256 "77c4e9a2584d475afd3df9eb411634285588ba12f98204fb936194f1b303d4fb"
      define_method(:install) do
        bin.install "diskclean"
      end
    end
  end

  test do
    system "#{bin}/diskclean", "--version"
  end
end
